package com.mabrouk.placepicker

object Constants {
  const val PLACE_LISTENER: String="PLACE_LISTENER"
  const val HAS_PlaceAutocomplete: String="HAS_PlaceAutocomplete"
  const val FILTER_COUNTRY:String="FILTER_COUNTRY"
    const val MAP_TYPE: String="MAP_TYPE"
  const val SHOW_LAT_LONG_INTENT = "SHOW_LAT_LONG_INTENT"
  const val INITIAL_LATITUDE_INTENT = "INITIAL_LATITUDE_INTENT"
  const val INITIAL_LONGITUDE_INTENT = "INITIAL_LONGITUDE_INTENT"
  const val INITIAL_ZOOM_INTENT = "INITIAL_ZOOM_INTENT"
  const val ADDRESS_REQUIRED_INTENT = "ADDRESS_REQUIRED_INTENT"
  const val HIDE_MARKER_SHADOW_INTENT = "HIDE_MARKER_SHADOW_INTENT"
  const val MARKER_DRAWABLE_RES_INTENT = "MARKER_DRAWABLE_RES_INTENT"
  const val MARKER_COLOR_RES_INTENT = "MARKER_COLOR_RES_INTENT"
  const val FAB_COLOR_RES_INTENT = "FAB_COLOR_RES_INTENT"
  const val PRIMARY_TEXT_COLOR_RES_INTENT = "PRIMARY_TEXT_COLOR_RES_INTENT"
  const val SECONDARY_TEXT_COLOR_RES_INTENT = "PRIMARY_TEXT_COLOR_RES_INTENT"
  const val DEFAULT_LATITUDE = 40.748672
  const val DEFAULT_LONGITUDE = -73.985628
  const val DEFAULT_ZOOM = 14.0F
  const val PLACE_PICKER_REQUEST = 100
  const val PLACE_PICKER_REQUEST_code = 101
  const val ADDRESS_INTENT = "ADDRESS_INTENT"
  const val IS_INDOOR_ENABLE="IS_INDOOR_ENABLE"
  const val IS_TRAFFIC_ENABLE="IS_TRAFFIC_ENABLE"
  var placePickerListener:PlacePickerListener?=null
}